/**
 * DASHBOARD
 */
export const SET_DASHBOARD_SUMMARY = "SET_DASHBOARD_SUMMARY ";
export const SET_TRANSACTION_TABLE_DATA = "SET_TRANSACTION_TABLE_DATA";
export const SET_TRANSACTION_ID = "SET_TRANSACTION_ID ";
export const SET_TRANSACTION_DETAILS = "SET_TRANSACTION_DETAILS";
export const SET_SINGLE_TRANSACTION = "SET_SINGLE_TRANSACTION";
