/**
 * Batch File Search
 */
export const SET_BATCH_FILE_SEARCH_ROWS = "SET_BATCH_FILE_SEARCH_ROWS";
export const SET_BATCH_FILE_CURR_PAGE_NUM = "SET_BATCH_FILE_CURR_PAGE_NUM";
export const SET_BATCH_FILE_NO_OF_ROWS = "SET_BATCH_FILE_NO_OF_ROWS";

/**
 * Batch Search
 */
export const SET_BATCH_SEARCH_ROWS = "SET_BATCH_SEARCH_ROWS";
export const SET_BATCH_CURR_PAGE_NUM = "SET_BATCH_CURR_PAGE_NUM";
export const SET_BATCH_NO_OF_ROWS = "SET_BATCH_NO_OF_ROWS";

export const SET_BATCH_SEARCH_FORM_DATA = "SET_BATCH_SEARCH_FORM_DATA";

export const SET_BATCH_PAGE_DATA = "SET_BATCH_PAGE_DATA";
