export const SET_OVERVIEW_DETAILS = "SET_OVERVIEW_DETAILS";
export const SET_DEBITOR_DETAILS = "SET_DEBITOR_DETAILS";
export const SET_CREDITOR_DETAILS = "SET_CREDITOR_DETAILS";
export const SET_PAYMENT_ID_DETAILS = "SET_PAYMENT_ID_DETAILS";
export const SET_FLEX_DETAILS = "SET_FLEX_DETAILS";
export const SET_PACS_MESSAGES = "SET_PACS_MESSAGES";
