/**
 * Search Transaction
 */
export const SET_SEARCH_TRANSACTION_SUMMARY = "SET_SEARCH_TRANSACTION_SUMMARY ";
export const SET_TRANSACTION_TABLE_DATA = "SET_TRANSACTION_TABLE_DATA";
export const SET_TRANSACTION_ID = "SET_TRANSACTION_ID ";
export const SET_TRANSACTION_DETAILS = "SET_TRANSACTION_DETAILS";
export const SET_SINGLE_TRANSACTION = "SET_SINGLE_TRANSACTION";
export const SET_SEARCH_TRANSACTION_FORMDATA =
  "SET_SEARCH_TRANSACTION_FORMDATA";

export const SET_SELECTED_TRANSACTIONS_ID = "SET_SELECTED_TRANSACTIONS_ID";
